region: ap-northeast-1
cluster: dev-codedeploy-practice
service: backend-blue
service_definition: ecs-service-def.json
task_definition: ecs-task-def.json
timeout: 10m
plugins:
  - name: tfstate
    config:
      path: ../../terraform.tfstate
filter_command: peco
appspec: null
